# Generated by Django 4.0 on 2022-06-25 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsianapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_species_model',
            name='examinations_code',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='parsianapp.examinationscourse'),
        ),
    ]
