# Generated by Django 4.0 on 2022-06-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsianapp', '0002_personal_species_model_examinations_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease_model',
            name='examinations_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
