# Generated by Django 4.0 on 2022-06-28 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsianapp', '0004_person_assessment_model_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulting_model',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consulting', to='parsianapp.personal_species_model'),
        ),
        migrations.AddField(
            model_name='examinations_model',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examinations', to='parsianapp.personal_species_model'),
        ),
        migrations.AddField(
            model_name='experiments_model',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiment', to='parsianapp.personal_species_model'),
        ),
        migrations.AddField(
            model_name='final_theory_model',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final', to='parsianapp.personal_species_model'),
        ),
        migrations.AddField(
            model_name='para_clinic_model',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='para', to='parsianapp.personal_species_model'),
        ),
        migrations.AddField(
            model_name='personal_history_model',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personalhistory', to='parsianapp.personal_species_model'),
        ),
        migrations.DeleteModel(
            name='Summary_Of_Results',
        ),
    ]
