# Generated by Django 4.0 on 2022-06-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsianapp', '0006_job_history_model_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AlterField(
            model_name='personal_species_model',
            name='job_name',
            field=models.CharField(blank=True, default='ذکر نشده', max_length=20, null=True),
        ),
    ]
