# Generated by Django 4.0 on 2022-06-30 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsianapp', '0007_delete_person_alter_personal_species_model_job_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_species_model',
            name='job_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
