# Generated by Django 4.0 on 2022-07-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsianapp', '0009_final_theory_model_disease_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='final_theory_model',
            name='d_code',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
