# Generated by Django 4.0 on 2022-07-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsianapp', '0012_alter_final_theory_model_d_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_history_model',
            name='current_job_from',
        ),
        migrations.RemoveField(
            model_name='job_history_model',
            name='current_job_to',
        ),
        migrations.AddField(
            model_name='job_history_model',
            name='current_job_from_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job_history_model',
            name='current_job_from_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job_history_model',
            name='current_job_from_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job_history_model',
            name='current_job_to_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job_history_model',
            name='current_job_to_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job_history_model',
            name='current_job_to_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
