# Generated by Django 4.0 on 2022-07-02 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsianapp', '0013_remove_job_history_model_current_job_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_history_model',
            name='durations',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
