# Generated by Django 4.0 on 2022-07-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsianapp', '0015_alter_assessment_model_date_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment_model',
            name='assessments',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='job_history_model',
            name='current_job_from_day',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='job_history_model',
            name='current_job_from_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='job_history_model',
            name='current_job_from_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='job_history_model',
            name='current_job_to_day',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='job_history_model',
            name='current_job_to_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='job_history_model',
            name='current_job_to_year',
            field=models.IntegerField(default=0),
        ),
    ]
