# Generated by Django 4.0 on 2022-07-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsianapp', '0016_assessment_model_assessments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='para_clinic_model',
            name='espiro_tafsir',
            field=models.CharField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3')], max_length=50, null=True),
        ),
    ]
