# Generated by Django 4.0 on 2022-07-08 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsianapp', '0023_disease_model_age_disease_model_fathers_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease_model',
            name='order_number',
        ),
    ]
