# Generated by Django 4.0 on 2022-07-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsianapp', '0024_remove_disease_model_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease_model',
            name='order_number',
            field=models.IntegerField(choices=[(1, '1'), (10, '10'), (20, '20'), (30, '30'), (40, '40'), (50, '50')], default=1, null=True),
        ),
    ]
