# Generated by Django 4.0 on 2022-07-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsianapp', '0025_disease_model_order_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='para_clinic_model',
            old_name='oudio_tafsir',
            new_name='oudio_l_tafsir',
        ),
        migrations.AddField(
            model_name='para_clinic_model',
            name='oudio_r_tafsir',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='disease_model',
            name='order_number',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (10, '10'), (20, '20'), (30, '30'), (40, '40'), (50, '50')], default=1, null=True),
        ),
    ]
