# Generated by Django 4.0 on 2022-07-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsianapp', '0027_remove_para_clinic_model_oudio_l_tafsir_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='para_clinic_model',
            name='opto_meidan_hedat_l_ba',
        ),
        migrations.RemoveField(
            model_name='para_clinic_model',
            name='opto_meidan_hedat_l_bi',
        ),
        migrations.RemoveField(
            model_name='para_clinic_model',
            name='opto_meidan_hedat_r_ba',
        ),
        migrations.RemoveField(
            model_name='para_clinic_model',
            name='opto_meidan_hedat_r_bi',
        ),
        migrations.RemoveField(
            model_name='para_clinic_model',
            name='opto_rangi_hedat_l_ba',
        ),
        migrations.RemoveField(
            model_name='para_clinic_model',
            name='opto_rangi_hedat_l_bi',
        ),
        migrations.RemoveField(
            model_name='para_clinic_model',
            name='opto_rangi_hedat_r_ba',
        ),
        migrations.RemoveField(
            model_name='para_clinic_model',
            name='opto_rangi_hedat_r_bi',
        ),
        migrations.AddField(
            model_name='para_clinic_model',
            name='opto_meidan',
            field=models.CharField(blank=True, choices=[('normal', 'نرمال'), ('not_normal', 'غیر نرمال')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='para_clinic_model',
            name='opto_rangi',
            field=models.CharField(blank=True, choices=[('normal', 'نرمال'), ('not_normal', 'غیر نرمال')], max_length=50, null=True),
        ),
    ]
