# Generated by Django 4.0 on 2022-07-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsianapp', '0028_remove_para_clinic_model_opto_meidan_hedat_l_ba_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinations_model',
            name='not_normals',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
