# Generated by Django 4.0 on 2022-07-31 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsianapp', '0029_examinations_model_not_normals'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Submit_Company_Model',
        ),
        migrations.DeleteModel(
            name='Summary_Of_Results_Model',
        ),
        migrations.AddField(
            model_name='para_clinic_model',
            name='opto_hedat_l_status',
            field=models.CharField(blank=True, choices=[('adam_did', 'عدم دید'), ('fc', 'FC'), ('daraie_did', 'دارای دید')], max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='para_clinic_model',
            name='opto_hedat_r_status',
            field=models.CharField(blank=True, choices=[('adam_did', 'عدم دید'), ('fc', 'FC'), ('daraie_did', 'دارای دید')], max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='para_clinic_model',
            name='opto_l',
            field=models.CharField(blank=True, choices=[('normal', 'نرمال'), ('not_normal', 'غیر نرمال')], max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='para_clinic_model',
            name='opto_r',
            field=models.CharField(blank=True, choices=[('normal', 'نرمال'), ('not_normal', 'غیر نرمال')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='assessment_model',
            name='assessments',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='assessment_model',
            name='kar_shenas',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='assessment_model',
            name='kar_shenas_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='assessment_model',
            name='required_description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='consulting_model',
            name='first_reason',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='consulting_model',
            name='first_result',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='consulting_model',
            name='first_type',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='consulting_model',
            name='second_reason',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='consulting_model',
            name='second_result',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='consulting_model',
            name='second_type',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='disease_model',
            name='examinations_code',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='disease_model',
            name='fathers_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='disease_model',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='examinations_model',
            name='asabi_des',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='examinations_model',
            name='colie_des',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='examinations_model',
            name='eskelety_des',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='examinations_model',
            name='eye_des',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='examinations_model',
            name='ghalb_des',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='examinations_model',
            name='gosh_des',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='examinations_model',
            name='local_des',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='examinations_model',
            name='not_normals',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='examinations_model',
            name='other',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='examinations_model',
            name='ravan_des',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='examinations_model',
            name='rie_des',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='examinations_model',
            name='sar_des',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='examinations_model',
            name='shekam_des',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='examinations_model',
            name='skin_des',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='examinationscourse',
            name='doctor',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='examinationscourse',
            name='employer',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='examinationscourse',
            name='examinations_code',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='experiments_model',
            name='first_result',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='experiments_model',
            name='first_type',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='experiments_model',
            name='second_result',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='experiments_model',
            name='second_type',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='experiments_model',
            name='third_result',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='experiments_model',
            name='third_type',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='final_theory_model',
            name='mashrot_reason',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='final_theory_model',
            name='problems',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='final_theory_model',
            name='rad_reason',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='final_theory_model',
            name='reason',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='final_theory_model',
            name='recommendations',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='job_history_model',
            name='current_job',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='job_history_model',
            name='current_job_duty',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='job_history_model',
            name='current_job_reason',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='job_history_model',
            name='previous_job',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='job_history_model',
            name='previous_job_duty',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='job_history_model',
            name='previous_job_from',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='job_history_model',
            name='previous_job_reason',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='job_history_model',
            name='previous_job_to',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='job_history_model',
            name='second_current_job',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='job_history_model',
            name='second_current_job_duty',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='job_history_model',
            name='second_current_job_from',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='job_history_model',
            name='second_current_job_reason',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='job_history_model',
            name='second_current_job_to',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='job_history_model',
            name='second_previous_job',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='job_history_model',
            name='second_previous_job_duty',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='job_history_model',
            name='second_previous_job_from',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='job_history_model',
            name='second_previous_job_reason',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='job_history_model',
            name='second_previous_job_to',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='para_clinic_model',
            name='audio_l_tafsir',
            field=models.CharField(blank=True, choices=[('normal', 'نرمال'), ('kahesh_shenavai_hedayati', 'کاهش شنوایی هدایتی'), ('kahesh_shenavai_hesi_asabi', 'کاهش شنوایی حسی عصبی'), ('kahesh_shenavai_nashi_az_seda', 'کاهش شنوایی ناشی از صدا'), ('toaman_hedayati_va_hesi_asabi', 'توامان هدایتی و حسی عصبی')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='para_clinic_model',
            name='audio_r_tafsir',
            field=models.CharField(blank=True, choices=[('normal', 'نرمال'), ('kahesh_shenavai_hedayati', 'کاهش شنوایی هدایتی'), ('kahesh_shenavai_hesi_asabi', 'کاهش شنوایی حسی عصبی'), ('kahesh_shenavai_nashi_az_seda', 'کاهش شنوایی ناشی از صدا'), ('toaman_hedayati_va_hesi_asabi', 'توامان هدایتی و حسی عصبی')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='para_clinic_model',
            name='espiro_fef',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='para_clinic_model',
            name='espiro_fev',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='para_clinic_model',
            name='espiro_fevvfvc',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='para_clinic_model',
            name='espiro_fvc',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='para_clinic_model',
            name='espiro_pef',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='para_clinic_model',
            name='espiro_tafsir',
            field=models.CharField(blank=True, choices=[('normal', 'نرمال'), ('ensedadi', 'انسدادی'), ('tahdidi', 'تحدیدی'), ('ensedadivtahdidi', 'انسدادی و تحدیدی'), ('again', 'نیاز به تکرار')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='para_clinic_model',
            name='espiro_vext',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='para_clinic_model',
            name='opto_meidan',
            field=models.CharField(blank=True, choices=[('normal', 'نرمال'), ('not_normal', 'غیر نرمال')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='para_clinic_model',
            name='opto_rangi',
            field=models.CharField(blank=True, choices=[('normal', 'نرمال'), ('not_normal', 'غیر نرمال')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='para_clinic_model',
            name='other_cxr',
            field=models.CharField(blank=True, choices=[('normal', 'نرمال'), ('not_normal', 'غیر نرمال')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='para_clinic_model',
            name='other_ecg',
            field=models.CharField(blank=True, choices=[('normal', 'نرمال'), ('not_normal', 'غیر نرمال'), ('not_ekhtesasi', 'تغییرات غیر اختصاصی'), ('again', 'نیاز به تکرار')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='para_clinic_model',
            name='other_result',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='personal_history_model',
            name='eighth_des',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='personal_history_model',
            name='eleventh_des_duration',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='personal_history_model',
            name='eleventh_des_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='personal_history_model',
            name='fifteenth_des',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='personal_history_model',
            name='fifth_des',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='personal_history_model',
            name='first_des',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='personal_history_model',
            name='fourteenth_des',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='personal_history_model',
            name='fourth_des',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='personal_history_model',
            name='ninth_des',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='personal_history_model',
            name='second_des',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='personal_history_model',
            name='seventh_des',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='personal_history_model',
            name='sixteenth_des',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='personal_history_model',
            name='sixth_des',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='personal_history_model',
            name='tenth_des_duration',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='personal_history_model',
            name='tenth_des_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='personal_history_model',
            name='third_des',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='personal_history_model',
            name='thirteenth_des_reason',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='personal_history_model',
            name='thirteenth_des_type',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='personal_history_model',
            name='twelfth_des',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='personal_species_model',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='personal_species_model',
            name='employer_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='personal_species_model',
            name='examinations_type',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='personal_species_model',
            name='fathers_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='personal_species_model',
            name='gender',
            field=models.CharField(choices=[('mard', 'مرد'), ('zan', 'زن')], default='mard', max_length=250),
        ),
        migrations.AlterField(
            model_name='personal_species_model',
            name='job_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='personal_species_model',
            name='marriage_status',
            field=models.CharField(choices=[('mojarad', 'مجرد'), ('motahel', 'متاحل')], default='mojarad', max_length=250),
        ),
        migrations.AlterField(
            model_name='personal_species_model',
            name='medical_exemption_reason',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='personal_species_model',
            name='military_status',
            field=models.CharField(choices=[('khedmat_karde', 'خدمت کرده'), ('moaf', 'معاف')], default='khedmat_karde', max_length=250),
        ),
        migrations.AlterField(
            model_name='personal_species_model',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='personal_species_model',
            name='raste',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
