# Generated by Django 4.0 on 2022-07-31 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsianapp', '0030_delete_submit_company_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_species_model',
            name='user',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
