# Generated by Django 4.0 on 2022-08-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsianapp', '0031_personal_species_model_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_species_model',
            name='examinations_type',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='personal_species_model',
            unique_together={('examinations_code', 'name', 'fathers_name')},
        ),
    ]
