# Generated by Django 4.0 on 2022-08-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsianapp', '0032_alter_personal_species_model_examinations_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_species_model',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
