# Generated by Django 4.0 on 2022-08-02 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsianapp', '0033_alter_personal_species_model_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='personal_species_model',
            unique_together={('examinations_code', 'name', 'fathers_name', 'age', 'personal_code')},
        ),
    ]
