# Generated by Django 4.0 on 2022-08-02 13:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsianapp', '0034_alter_personal_species_model_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_species_model',
            name='age',
            field=models.IntegerField(blank=True, default='', null=True, validators=[django.core.validators.MinValueValidator(1300), django.core.validators.MaxValueValidator(1400)]),
        ),
        migrations.AlterField(
            model_name='personal_species_model',
            name='fathers_name',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='personal_species_model',
            name='name',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='personal_species_model',
            name='personal_code',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
    ]
