# Generated by Django 4.0 on 2022-08-06 05:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsianapp', '0035_alter_personal_species_model_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='para_clinic_model',
            name='opto_date_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='para_clinic_model',
            name='opto_date_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personal_history_model',
            name='eleventh_des_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personal_history_model',
            name='tenth_des_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personal_species_model',
            name='age',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1300), django.core.validators.MaxValueValidator(1400)]),
        ),
        migrations.AlterField(
            model_name='personal_species_model',
            name='fathers_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='personal_species_model',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='personal_species_model',
            name='personal_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
