# Generated by Django 4.0 on 2022-08-08 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsianapp', '0037_alter_examinations_model_blood_pressure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_history_model',
            name='current_job_from_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job_history_model',
            name='current_job_from_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job_history_model',
            name='current_job_from_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job_history_model',
            name='current_job_to_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job_history_model',
            name='current_job_to_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job_history_model',
            name='current_job_to_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
