# Generated by Django 4.0 on 2022-08-08 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsianapp', '0038_alter_job_history_model_current_job_from_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_history_model',
            name='current_job_from_day',
        ),
        migrations.RemoveField(
            model_name='job_history_model',
            name='current_job_to_day',
        ),
    ]
