# Generated by Django 4.0 on 2022-08-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsianapp', '0040_alter_personal_species_model_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_species_model',
            name='name',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
