# Generated by Django 4.0 on 2022-08-10 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsianapp', '0041_alter_personal_species_model_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personal_species_model',
            old_name='date_day',
            new_name='species_date_day',
        ),
        migrations.RenameField(
            model_name='personal_species_model',
            old_name='date_month',
            new_name='species_date_month',
        ),
        migrations.RenameField(
            model_name='personal_species_model',
            old_name='date_year',
            new_name='species_date_year',
        ),
    ]
