# Generated by Django 4.0 on 2022-08-11 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsianapp', '0042_rename_date_day_personal_species_model_species_date_day_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessment_model',
            old_name='date_day',
            new_name='ass_date_day',
        ),
        migrations.RenameField(
            model_name='assessment_model',
            old_name='date_month',
            new_name='ass_date_month',
        ),
        migrations.RenameField(
            model_name='assessment_model',
            old_name='date_year',
            new_name='ass_date_year',
        ),
        migrations.RenameField(
            model_name='examinations_model',
            old_name='date_day',
            new_name='exa_date_day',
        ),
        migrations.RenameField(
            model_name='examinations_model',
            old_name='date_month',
            new_name='exa_date_month',
        ),
        migrations.RenameField(
            model_name='examinations_model',
            old_name='date_year',
            new_name='exa_date_year',
        ),
        migrations.RenameField(
            model_name='experiments_model',
            old_name='date_day',
            new_name='exp_date_day',
        ),
        migrations.RenameField(
            model_name='experiments_model',
            old_name='date_month',
            new_name='exp_date_month',
        ),
        migrations.RenameField(
            model_name='experiments_model',
            old_name='date_year',
            new_name='exp_date_year',
        ),
    ]
