# Generated by Django 4.0 on 2022-08-17 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsianapp', '0043_rename_date_day_assessment_model_ass_date_day_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examinationscourse',
            old_name='employer',
            new_name='specialist',
        ),
    ]
