# Generated by Django 4.0 on 2022-08-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsianapp', '0044_rename_employer_examinationscourse_specialist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_history_model',
            name='current_job_reason',
        ),
        migrations.RemoveField(
            model_name='job_history_model',
            name='previous_job',
        ),
        migrations.RemoveField(
            model_name='job_history_model',
            name='previous_job_duty',
        ),
        migrations.RemoveField(
            model_name='job_history_model',
            name='previous_job_from',
        ),
        migrations.RemoveField(
            model_name='job_history_model',
            name='previous_job_reason',
        ),
        migrations.RemoveField(
            model_name='job_history_model',
            name='previous_job_to',
        ),
        migrations.RemoveField(
            model_name='job_history_model',
            name='second_current_job',
        ),
        migrations.RemoveField(
            model_name='job_history_model',
            name='second_current_job_duty',
        ),
        migrations.RemoveField(
            model_name='job_history_model',
            name='second_current_job_from',
        ),
        migrations.RemoveField(
            model_name='job_history_model',
            name='second_current_job_reason',
        ),
        migrations.RemoveField(
            model_name='job_history_model',
            name='second_current_job_to',
        ),
        migrations.RemoveField(
            model_name='job_history_model',
            name='second_previous_job',
        ),
        migrations.RemoveField(
            model_name='job_history_model',
            name='second_previous_job_duty',
        ),
        migrations.RemoveField(
            model_name='job_history_model',
            name='second_previous_job_from',
        ),
        migrations.RemoveField(
            model_name='job_history_model',
            name='second_previous_job_reason',
        ),
        migrations.RemoveField(
            model_name='job_history_model',
            name='second_previous_job_to',
        ),
        migrations.AlterField(
            model_name='personal_species_model',
            name='examinations_type',
            field=models.CharField(choices=[('badv_estekhdam', 'بدو استخدام'), ('dore_e', 'دوره ای'), ('bazgasht_be_kar', 'بازگشت به کار')], default='mard', max_length=250),
        ),
        migrations.AlterField(
            model_name='personal_species_model',
            name='military_status',
            field=models.CharField(choices=[('khedmat_karde', 'خدمت کرده'), ('moaf', 'معاف'), ('khedmat_nakarde', 'خدمت نکرده')], default='khedmat_karde', max_length=250),
        ),
    ]
