# Generated by Django 4.0 on 2022-08-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsianapp', '0046_alter_personal_species_model_examinations_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease_model',
            name='p_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disease_model',
            name='p_examinations_code',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='disease_model',
            name='p_fathers_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='disease_model',
            name='p_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='disease_model',
            name='p_personal_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
