# Generated by Django 4.0 on 2022-08-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsianapp', '0048_disease_model_e_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='para_clinic_model',
            name='audio_l_three_ac',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='para_clinic_model',
            name='audio_l_three_bc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='para_clinic_model',
            name='audio_r_three_ac',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='para_clinic_model',
            name='audio_r_three_bc',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
