# Generated by Django 3.2.15 on 2022-10-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsianapp', '0050_auto_20221015_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_species_model',
            name='medical_exemption',
            field=models.CharField(blank=True, choices=[('pezeshki', 'پزشکی'), ('not_pezeshki', 'غیر پزشکی'), ('none', 'ندارد')], default='none', max_length=250, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='personal_species_model',
            unique_together=set(),
        ),
    ]
