# Generated by Django 3.2.15 on 2022-10-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsianapp', '0051_auto_20221016_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiments_model',
            name='ppd_status',
            field=models.CharField(blank=True, choices=[('normal', 'نرمال'), ('not_normal', 'غیر نرمال')], default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='experiments_model',
            name='se_status',
            field=models.CharField(blank=True, choices=[('normal', 'نرمال'), ('not_normal', 'غیر نرمال')], default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='personal_species_model',
            name='medical_exemption',
            field=models.CharField(blank=True, choices=[('none', 'ندارد'), ('pezeshki', 'پزشکی'), ('not_pezeshki', 'غیر پزشکی')], default='none', max_length=250, null=True),
        ),
    ]
