# Generated by Django 3.2.15 on 2022-12-08 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsianapp', '0054_auto_20221206_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examinationscourse',
            name='company',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='parsianapp.company'),
        ),
        migrations.AlterField(
            model_name='personal_species_model',
            name='examinations_code',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterModelTable(
            name='examinationscourse',
            table=None,
        ),
        migrations.AlterModelTable(
            name='personal_species_model',
            table='ExaminationsCourse',
        ),
    ]
