# Generated by Django 3.2.15 on 2022-12-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsianapp', '0055_auto_20221208_2051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_history_model',
            old_name='current_job',
            new_name='first_current_change_job_reason',
        ),
        migrations.RenameField(
            model_name='job_history_model',
            old_name='current_job_duty',
            new_name='first_current_job',
        ),
        migrations.RenameField(
            model_name='job_history_model',
            old_name='current_job_from_month',
            new_name='first_current_job_durations',
        ),
        migrations.RenameField(
            model_name='job_history_model',
            old_name='current_job_from_year',
            new_name='first_current_job_from_month',
        ),
        migrations.RenameField(
            model_name='job_history_model',
            old_name='current_job_to_month',
            new_name='first_current_job_from_year',
        ),
        migrations.RenameField(
            model_name='job_history_model',
            old_name='current_job_to_year',
            new_name='first_current_job_to_month',
        ),
        migrations.RenameField(
            model_name='job_history_model',
            old_name='durations',
            new_name='first_current_job_to_year',
        ),
        migrations.AddField(
            model_name='job_history_model',
            name='first_current_job_duty',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='job_history_model',
            name='first_previous_change_job_reason',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='job_history_model',
            name='first_previous_job',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='job_history_model',
            name='first_previous_job_durations',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job_history_model',
            name='first_previous_job_duty',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='job_history_model',
            name='first_previous_job_from_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job_history_model',
            name='first_previous_job_from_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job_history_model',
            name='first_previous_job_to_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job_history_model',
            name='first_previous_job_to_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job_history_model',
            name='second_current_change_job_reason',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='job_history_model',
            name='second_current_job',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='job_history_model',
            name='second_current_job_durations',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job_history_model',
            name='second_current_job_duty',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='job_history_model',
            name='second_current_job_from_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job_history_model',
            name='second_current_job_from_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job_history_model',
            name='second_current_job_to_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job_history_model',
            name='second_current_job_to_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job_history_model',
            name='second_previous_change_job_reason',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='job_history_model',
            name='second_previous_job',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='job_history_model',
            name='second_previous_job_durations',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job_history_model',
            name='second_previous_job_duty',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='job_history_model',
            name='second_previous_job_from_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job_history_model',
            name='second_previous_job_from_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job_history_model',
            name='second_previous_job_to_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job_history_model',
            name='second_previous_job_to_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
