# Generated by Django 3.2.15 on 2022-12-09 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsianapp', '0056_auto_20221208_2228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_history_model',
            old_name='first_previous_job_from_month',
            new_name='first_previous_job_from',
        ),
        migrations.RenameField(
            model_name='job_history_model',
            old_name='first_previous_job_from_year',
            new_name='first_previous_job_to',
        ),
        migrations.RenameField(
            model_name='job_history_model',
            old_name='first_previous_job_to_month',
            new_name='second_previous_job_from',
        ),
        migrations.RenameField(
            model_name='job_history_model',
            old_name='first_previous_job_to_year',
            new_name='second_previous_job_to',
        ),
        migrations.RemoveField(
            model_name='job_history_model',
            name='second_previous_job_from_month',
        ),
        migrations.RemoveField(
            model_name='job_history_model',
            name='second_previous_job_from_year',
        ),
        migrations.RemoveField(
            model_name='job_history_model',
            name='second_previous_job_to_month',
        ),
        migrations.RemoveField(
            model_name='job_history_model',
            name='second_previous_job_to_year',
        ),
    ]
