# Generated by Django 3.2.15 on 2022-12-10 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsianapp', '0057_auto_20221209_1408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disease_model',
            old_name='age',
            new_name='breath_year',
        ),
        migrations.RenameField(
            model_name='examinations_model',
            old_name='blood_pressure',
            new_name='max_blood_pressure',
        ),
        migrations.AddField(
            model_name='examinations_model',
            name='min_blood_pressure',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='para_clinic_model',
            name='description_cxr',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='para_clinic_model',
            name='description_ecg',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='para_clinic_model',
            name='opto_Description',
            field=models.CharField(blank=True, choices=[('normal', 'نرمال'), ('not_normal', 'غیر نرمال')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='personal_species_model',
            name='examinations_code',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='parsianapp.examinationscourse'),
        ),
        migrations.AlterModelTable(
            name='personal_species_model',
            table=None,
        ),
    ]
