# Generated by Django 3.2.15 on 2022-12-10 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsianapp', '0058_auto_20221210_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examinationscourse',
            old_name='company',
            new_name='current_company',
        ),
    ]
