# Generated by Django 3.2.15 on 2022-12-10 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsianapp', '0059_rename_company_examinationscourse_current_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examinationscourse',
            old_name='current_company',
            new_name='company',
        ),
        migrations.AlterModelTable(
            name='examinationscourse',
            table='company',
        ),
    ]
