# Generated by Django 3.2.15 on 2022-12-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsianapp', '0061_alter_personal_species_model_personal_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disease_model',
            old_name='breath_year',
            new_name='age',
        ),
        migrations.AlterField(
            model_name='personal_species_model',
            name='personal_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
